{% set name = "xcube-cci" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/esa-cci/xcube-cci/archive/v{{ version }}.tar.gz
  sha256: d9d88a5bde23b2f3e6d06b75bde0d9c2b6ad717e0b819ded9632ae08586c62d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp >=3.6
    - lxml >=4.5
    - numpy >=2.0
    - pydap >=3.4,<=3.5.3
    - rioxarray
    - xarray >=2025.4.0
    - xcube >=1.8.0
    - xvec >=0.5.0
    - zarr <3

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_cci

about:
  summary: xcube plugin for the ESA CCI Open Data Portal
  home: https://github.com/esa-cci/xcube-cci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cci is an xcube plugin that allows generating data cubes from the ESA CCI Open Data Portal.
  doc_url: https://github.com/esa-cci/xcube-cci/blob/master/README.md
  dev_url: https://github.com/esa-cci/xcube-cci

extra:
  recipe-maintainers:
    - pont-us
    - TejasMorbagal
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
    - konstntokas
    - b-yogesh
    - clarasb
