{% set name = "xcube-cci" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cci/archive/v{{ version }}.tar.gz
  sha256: 6c38974016986153506c061c6066a704455613d44d5c94160eb916aaa1dbd62c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.6
    - lxml >=4.5
    - nest-asyncio >=1.3
    - pydap >=3.3
    - xcube >=0.9

test:
  imports:
    - xcube_cci

about:
  summary: xcube plugin for the ESA CCI Open Data Portal
  home: https://github.com/dcs4cop/xcube-cci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cci is an xcube plugin that allows generating data cubes from the ESA CCI Open Data Portal.
  doc_url: https://github.com/dcs4cop/xcube-cci/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cci

extra:
  recipe-maintainers:
    - pont-us
    - TejasMorbagal
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
