{% set name = "xcube-cci" %}
{% set version = "0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cci/archive/v{{ version }}.tar.gz
  sha256: 6a7d11a6780737c2fa98e1f3815ee55a92dbf8c7466ec7ea904e071371c1defe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - aiohttp >=3.6
    - lxml >=4.5
    - nest-asyncio >=1.3
    - pydap ==3.3
    - xcube >=1.0.3
    - gdal >=3.0,<3.6.3

test:
  imports:
    - xcube_cci

about:
  summary: xcube plugin for the ESA CCI Open Data Portal
  home: https://github.com/dcs4cop/xcube-cci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cci is an xcube plugin that allows generating data cubes from the ESA CCI Open Data Portal.
  doc_url: https://github.com/dcs4cop/xcube-cci/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cci

extra:
  recipe-maintainers:
    - pont-us
    - TejasMorbagal
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
