{% set python_min = '3.10' %}
{% set name = "xcube-cci" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esa-cci/xcube-cci/archive/v{{ version }}.tar.gz
  sha256: 31ae1b8f8fc29619537cb114954e3914f029a98b385550b568d7f6eacd2d3783

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - aiohttp >=3.6
    - lxml >=4.5
    - nest-asyncio >=1.3
    - numpy >=2.0
    - pydap >=3.4
    - rioxarray
    - xcube >=1.4.0
    - xvec

test:
  requires:
    - python {{ python_min }}
  imports:
    - xcube_cci

about:
  summary: xcube plugin for the ESA CCI Open Data Portal
  home: https://github.com/esa-cci/xcube-cci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cci is an xcube plugin that allows generating data cubes from the ESA CCI Open Data Portal.
  doc_url: https://github.com/esa-cci/xcube-cci/blob/master/README.md
  dev_url: https://github.com/esa-cci/xcube-cci

extra:
  recipe-maintainers:
    - pont-us
    - TejasMorbagal
    - TonioF
    - forman
    - AliceBalfanz
    - thomasstorm
    - ruchimotwaniBC
    - konstntokas
    - b-yogesh
