{% set name = "xcube-cci" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcs4cop/xcube-cci/archive/v{{ version }}.tar.gz
  sha256: c4bc27af019125e30f0457bb90678665b2e5d902ab50635ff3b577653627d6f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.6
    - aiohttp >=3.6
    - lxml >=4.5
    - nest-asyncio >=1.3
    - pydap >=3.2
    - xcube >=0.9

test:
  imports:
    - xcube_cci

about:
  summary: xcube plugin for the ESA CCI Open Data Portal
  home: https://github.com/dcs4cop/xcube-cci
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: xcube-cci is an xcube plugin that allows generating data cubes from the ESA CCI Open Data Portal.
  doc_url: https://github.com/dcs4cop/xcube-cci/blob/master/README.md
  dev_url: https://github.com/dcs4cop/xcube-cci

extra:
  recipe-maintainers:
    - pont-us
    - dzelge
    - TonioF
    - forman
    - AliceBalfanz
